# lib/install/agents.sh — Per-agent installer functions.
#
# Source this from install.sh. Defines:
#   - install_claude
#   - install_pi
#   - install_subagents
#
# Requires:
#   log_info / log_ok / log_warn / log_err (from logging.sh)
#   run / log_dry (from logging.sh)
#   ensure_symlink / ensure_merged_skills_into / ensure_file (from symlink.sh)
#   install_sop (from sop.sh)
#
# Reads/writes:
#   TARGET_ROOT, SOURCE_DIR, DIR_CLAUDE, DIR_PI, DIR_AGENTS, VERSION,
#   CLAUDE_SKILLS_MODE, AGENTS

# REGRESSION-GUARD PROBE: claude-install
install_claude() {
  log_info "Installing for Claude Code..."

  local claude_root="$TARGET_ROOT/${DIR_CLAUDE}"
  local skills_link="$claude_root/skills"
  local wrapper="$claude_root/CLAUDE.md"

  # Resolve / create the wrapper directory.
  [[ -d "$claude_root" ]] || run mkdir -p "$claude_root"

  case "$CLAUDE_SKILLS_MODE" in
    merge)
      # Pre-create $skills_link as an empty real directory so
      # ensure_merged_skills_into() takes the per-skill merge path
      # (matching ~/.pi/agent/skills/ behavior). Falling back to a
      # tree-level symlink here would silently shadow any other skills
      # the user later drops into ~/.claude/skills/.
      # Idempotent: skip if it already exists (file, symlink, or dir).
      if [[ ! -e "$skills_link" ]] && [[ ! -L "$skills_link" ]]; then
        run mkdir -p "$skills_link"
      fi
      ensure_merged_skills_into "$SOURCE_DIR/skills" "$skills_link"
      ;;
    replace)
      if [[ -e "$skills_link" ]] && [[ ! -L "$skills_link" ]]; then
        local stamp
        stamp="$(date +%Y%m%d-%H%M%S)"
        log_warn "replace: backing up $skills_link -> $skills_link.bak.$stamp"
        run mv "$skills_link" "$skills_link.bak.$stamp"
      fi
      ensure_symlink "$skills_link" "$SOURCE_DIR/skills"
      ;;
    skip)
      log_info "skipping Claude skills (--claude-skills-mode=skip)"
      ;;
  esac

  # Wrapper content with marker comments so --uninstall can find it.
  local content
  content="$(cat <<EOF
# tree-monstor-loader:DO-NOT-EDIT-START
# Auto-generated by install.sh v${VERSION}. Safe to remove via:
#   ./install.sh --uninstall
#
# Pulls AGENTS.md and SOUL.md from the tree_monstor source so any edit
# there propagates immediately (this file is regenerated on each run).

@${SOURCE_DIR}/AGENTS.md
@${SOURCE_DIR}/SOUL.md
# tree-monstor-loader:DO-NOT-EDIT-END
EOF
)"

  ensure_file "$wrapper" "$content"
}

# REGRESSION-GUARD PROBE: pi-install
install_pi() {
  log_info "Installing for Pi Agent..."
  local pi_root="$TARGET_ROOT/${DIR_PI}"

  # Pi's documented global resource dir is ~/.pi/agent/ (see pi
  # docs/usage.md:100 and docs/skills.md#locations). Earlier versions of
  # this script installed to ~/.pi/ (e.g. ~/.pi/AGENTS.md,
  # ~/.pi/skills), which pi silently ignores — AGENTS.md was never
  # loaded at startup and skills were never discovered.
  local agent_root="$pi_root/agent"
  [[ -d "$agent_root" ]] || run mkdir -p "$agent_root"

  # AGENTS.md: single symlink at the correct location.
  ensure_symlink "$agent_root/AGENTS.md" "$SOURCE_DIR/AGENTS.md"

  # Skills: merge per-skill symlinks into ~/.pi/agent/skills/.
  # Use a dedicated merge function so we never clobber other global skills
  # the user may have placed there (e.g. ~/.pi/agent/skills/gsap-*).
  # Pre-create the dir so ensure_merged_skills_into() takes the merge path
  # instead of falling back to a tree-level symlink (which would shadow any
  # skills the user adds later).
  [[ -d "$agent_root/skills" ]] || [[ -L "$agent_root/skills" ]] || run mkdir -p "$agent_root/skills"
  ensure_merged_skills_into "$SOURCE_DIR/skills" "$agent_root/skills"

  # SOUL.md is NOT installed globally. See plan output above for rationale.

  # Subagents: per-file symlinks into ~/.agents/<name>.md (user-scope).
  # pi-subagents discovers them automatically and they take precedence
  # over builtins but lose to project-scope agents.
  install_subagents
}

# REGRESSION-GUARD PROBE: subagent-install
# Installs tree_monstor's subagents to ~/.agents/<name>.md
# (user-scope). pi-subagents discovers them automatically; they take
# precedence over builtins but lose to project-scope agents.
#
# Layout:
#   - Source: $SOURCE_DIR/agents/<name>.md
#   - Target: $TARGET_ROOT/.agents/<name>.md  (symlink)
#
# Conflicts: if a non-symlink file already exists at the target, we skip
# with a warning (preserves user-owned subagents, mirroring skill merge).
install_subagents() {
  local src_agents_dir="$SOURCE_DIR/agents"
  if [[ ! -d "$src_agents_dir" ]]; then
    return 0
  fi

  local dst_agents_dir="$TARGET_ROOT/${DIR_AGENTS}"
  [[ -d "$dst_agents_dir" ]] || run mkdir -p "$dst_agents_dir"

  shopt -s nullglob
  local agent_path installed=0 updated=0 ok=0 skipped=0
  for agent_path in "$src_agents_dir"/*.md; do
    local name
    name="$(basename "$agent_path")"
    local link="$dst_agents_dir/$name"
    local target_abs
    target_abs="$(abs_path "$agent_path")"

    if [[ -L "$link" ]]; then
      # Existing symlink — check target matches our source.
      local current
      current="$(readlink "$link")"
      if [[ "$current" == "$target_abs" ]]; then
        log_ok "subagent OK: $link -> $target_abs"
        ok=$((ok + 1))
        continue
      fi
      # Wrong target — ensure_symlink() will repair it (logs "wrong target,
      # repairing" + "symlink created").
      ensure_symlink "$link" "$agent_path"
      updated=$((updated + 1))
      continue
    fi

    # Not a symlink — either missing (create) or regular file (skip).
    if [[ -e "$link" ]]; then
      log_warn "subagent: target exists and is not a symlink, skipping: $link"
      skipped=$((skipped + 1))
      continue
    fi

    # Missing — create new (ensure_symlink() logs "symlink created").
    ensure_symlink "$link" "$agent_path"
    installed=$((installed + 1))
  done
  shopt -u nullglob

  local total=$((installed + updated + ok + skipped))
  if (( total > 0 )); then
    log_info "subagents: installed=$installed, updated=$updated, ok=$ok, skipped=$skipped"
  fi
}