#!/usr/bin/env python3
"""
compression_executor.py — Layer 2+3: Decision + Execution

Given a session that has been flagged as high-pressure, this script:

  LAYER 2 — Decision:
    1. Re-check pressure using context_pressure_monitor's logic
    2. Decide: compress in-place OR fork (if pressure too high)
    3. If compress: call compression_summarizer to get a summary
    4. If fork: just call the existing fork queue processor

  LAYER 3 — Execution (compress path):
    1. Generate a synthetic "summary anchor" message
    2. Mark old messages as `active = 0` (preserve them in DB, but model
       won't see them in next API call)
    3. Insert the summary as a new system-role message
    4. Update sessions.compressed_summary column (if exists) or fall back
       to writing to handoffs/

This is the actual "compression" — the model gets a fresh context window
with the summary at the top, then resumes with the last 4 exchanges.

Threshold logic:
  - pressure 0.85-1.20 → compress (cheap, fast)
  - pressure > 1.20    → fork (compress can't save it)

Usage:
  compression_executor.py <session_id> [--dry-run] [--force]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# Reuse the summarizer's partition + extractive logic
sys.path.insert(0, str(Path(__file__).parent))
from compression_summarizer import (
    summarize_session,
    load_session_messages,
    partition_head_tail,
    extractive_summary,
    call_llm_summarize,
    TARGET_SUMMARY_TOKENS,
    COMPRESS_PRESSURE,
    FORK_PRESSURE,
    get_state_db,
    PROFILE_HOME,
    KEEP_LAST_EXCHANGES,
    HERMES_HOME,
)


# === Layer 2: Decision ===

def get_session_pressure(conn: sqlite3.Connection, sid: str) -> Tuple[float, Dict[str, Any]]:
    """Re-compute pressure for a specific session (mirrors context_pressure_monitor)."""
    cur = conn.execute("""
        SELECT message_count, api_call_count, input_tokens, output_tokens
        FROM sessions WHERE id = ?
    """, (sid,))
    row = cur.fetchone()
    if not row:
        return 0.0, {}
    msgs, api, in_tok, out_tok = row
    p_api = (api or 0) / 200
    p_msgs = (msgs or 0) / 300
    p_tok = ((in_tok or 0) / 200_000) / max(api or 1, 1)
    pressure = max(p_api, p_msgs, p_tok)
    return pressure, {
        "message_count": msgs or 0,
        "api_call_count": api or 0,
        "input_tokens": in_tok or 0,
        "output_tokens": out_tok or 0,
    }


def decide_action(pressure: float) -> str:
    """Decide what to do based on pressure."""
    if pressure >= FORK_PRESSURE:
        return "fork"
    elif pressure >= COMPRESS_PRESSURE:
        return "compress"
    else:
        return "skip"


# === Layer 3: Execution ===

def execute_compress(
    sid: str,
    summary_text: str,
    head_count: int,
    tail_count: int,
    method: str,
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Apply compression to a session:
    1. Generate a synthetic summary message
    2. Mark old head messages as `active = 0` (hidden from model)
    3. Insert summary as a new system-role message
    4. Write handoff file for /rollback safety
    """
    conn = sqlite3.connect(str(PROFILE_HOME / "state.db"))
    result = {
        "sid": sid,
        "action": "compress",
        "method": method,
        "head_compressed": head_count,
        "tail_preserved": tail_count,
        "summary_length": len(summary_text),
    }

    if dry_run:
        result["dry_run"] = True
        result["would_deactivate"] = head_count
        result["would_activate"] = 1  # the summary message
        conn.close()
        return result

    try:
        # Step 1: Find the highest active message id
        cur = conn.execute("""
            SELECT MAX(id) FROM messages WHERE session_id = ? AND active = 1
        """, (sid,))
        next_id = (cur.fetchone()[0] or 0) + 1

        # Step 2: Mark head messages as inactive (we partitioned by keep_last
        # in the summarizer, but here we partition again to be safe)
        messages = load_session_messages(conn, sid)
        head, tail = partition_head_tail(messages, KEEP_LAST_EXCHANGES)

        if len(head) == 0:
            result["action_taken"] = "noop"
            result["reason"] = "no head to compress"
            return result

        # Mark all head messages as inactive
        head_ids = [m["id"] for m in head]
        placeholders = ",".join("?" * len(head_ids))
        cur = conn.execute(f"""
            UPDATE messages SET active = 0, observed = 1
            WHERE id IN ({placeholders})
        """, head_ids)
        result["deactivated"] = cur.rowcount

        # Step 3: Insert summary as a system message at the front
        summary_msg = f"""[CONTEXT COMPRESSION — Auto-generated by long-task-resilience subagent]

The previous {head_count} messages have been compressed into the summary below.
{head_count} messages were summarized using method="{method}".
{tail_count} recent messages remain verbatim (preserved as the "tail").

=== COMPRESSED HISTORY (summary) ===

{summary_text}

=== END COMPRESSED HISTORY ===

You are now continuing with a fresh context window. Resume work based on the
goal/decisions/current state in the summary above, plus the recent exchanges
preserved below."""

        ts = datetime.now(timezone.utc).timestamp()
        conn.execute("""
            INSERT INTO messages (
                session_id, role, content, tool_name, tool_call_id,
                timestamp, token_count, finish_reason, active, observed
            ) VALUES (?, ?, ?, NULL, NULL, ?, NULL, 'compression_anchor', 1, 0)
        """, (sid, "system", summary_msg, ts))
        result["summary_message_id"] = next_id

        # Step 4: Update session metadata
        conn.execute("""
            UPDATE sessions
            SET message_count = (SELECT COUNT(*) FROM messages WHERE session_id = ? AND active = 1)
            WHERE id = ?
        """, (sid, sid))

        # Step 5: Write handoff file (for /rollback safety)
        handoffs_dir = PROFILE_HOME / "handoffs"
        handoffs_dir.mkdir(parents=True, exist_ok=True)
        safe_sid = sid.replace("/", "_").replace(":", "_")
        handoff_file = handoffs_dir / f"{safe_sid}.compression.md"
        handoff_file.write_text(f"""# Compression Handoff — {sid}

**Compressed at**: {datetime.now(timezone.utc).isoformat()}
**Method**: {method}
**Head compressed**: {head_count} messages
**Tail preserved**: {tail_count} messages

## Summary

{summary_text}

## How to undo

If this compression loses important context, the original messages are
preserved in the messages table with `active = 0`. To restore:

```sql
UPDATE messages SET active = 1 WHERE session_id = '{sid}' AND observed = 1;
DELETE FROM messages WHERE session_id = '{sid}' AND finish_reason = 'compression_anchor';
```
""")
        result["handoff_file"] = str(handoff_file)

        conn.commit()
        result["action_taken"] = "compressed"
    except sqlite3.OperationalError as e:
        result["action_taken"] = "error"
        result["error"] = str(e)
    finally:
        conn.close()

    return result


def execute_fork(sid: str, dry_run: bool = False) -> Dict[str, Any]:
    """Fork the session: archive it, queue a fresh session for the next user message.

    This is delegated to the existing process_fork_queue.py logic — we just
    append a fork request to the queue.
    """
    result: Dict[str, Any] = {"sid": sid, "action": "fork"}

    if dry_run:
        result["dry_run"] = True
        return result

    fork_queue = PROFILE_HOME / "session_fork_queue.jsonl"
    entry = {
        "session_id": sid,
        "queued_at": datetime.now(timezone.utc).isoformat(),
        "reason": "compression_threshold_exceeded",
        "trigger": "compression_executor",
    }
    with open(fork_queue, "a") as f:
        f.write(json.dumps(entry) + "\n")
    result["queued"] = True
    return result


# === Main ===

def process_session(
    sid: str,
    api_base: Optional[str] = None,
    api_key: Optional[str] = None,
    model: Optional[str] = None,
    force: bool = False,
    dry_run: bool = False,
) -> Dict[str, Any]:
    """Process one session: decide + execute."""
    conn = get_state_db()
    try:
        pressure, stats = get_session_pressure(conn, sid)
    finally:
        conn.close()

    action = decide_action(pressure)
    print(f"  📊 Session {sid[:24]}: pressure={pressure:.1%} → action={action}")

    if action == "skip" and not force:
        return {
            "sid": sid,
            "action": "skip",
            "pressure": pressure,
            "stats": stats,
            "reason": "pressure below compress threshold",
        }

    if action == "fork":
        return execute_fork(sid, dry_run)

    # Compress path (action == "compress" OR force with action == "skip")
    print(f"  📝 Summarizing {sid[:24]}...")
    summary_result = summarize_session(sid, api_base, api_key, model)

    if "error" in summary_result:
        return {
            "sid": sid,
            "action": "compress",
            "error": summary_result["error"],
        }

    return execute_compress(
        sid=sid,
        summary_text=summary_result["summary"],
        head_count=summary_result["head_count"],
        tail_count=summary_result["tail_count"],
        method=summary_result["method"],
        dry_run=dry_run,
    )


def load_llm_config() -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """Load LLM config from .env (profile first, then root)."""
    api_base = api_key = model = None
    env_candidates = [PROFILE_HOME / ".env", HERMES_HOME / ".env"]
    env_content = ""
    for env_file in env_candidates:
        if env_file.exists():
            env_content += env_file.read_text() + "\n"

    for key_name in ("MINIMAX_URL", "MINIMAX_BASE_URL", "LLM_API_BASE", "OPENAI_BASE_URL", "OPENROUTER_BASE_URL"):
        m = re.search(rf"{key_name}=([^\s\n]+)", env_content)
        if m:
            api_base = m.group(1).strip().strip('"').strip("'")
            break
    for key_name in ("MINIMAX_API_KEY", "LLM_API_KEY", "OPENAI_API_KEY", "OPENROUTER_API_KEY"):
        m = re.search(rf"{key_name}=([^\s\n]+)", env_content)
        if m:
            api_key = m.group(1).strip().strip('"').strip("'")
            break
    m = re.search(r"(?:MINIMAX_MODEL|LLM_MODEL|MODEL)=([^\s\n]+)", env_content)
    if m:
        model = m.group(1).strip().strip('"').strip("'")
    if not model:
        model = "MiniMax-M3"
    return api_base, api_key, model


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("session_id", nargs="?", help="Session ID to process (or 'auto' for all high-pressure sessions)")
    parser.add_argument("--force", action="store_true", help="Force compress even if below threshold")
    parser.add_argument("--dry-run", action="store_true", help="Report but don't modify state.db")
    parser.add_argument("--api-base", help="Override LLM API base")
    parser.add_argument("--api-key", help="Override LLM API key")
    parser.add_argument("--model", help="Override LLM model name")
    parser.add_argument("--json", action="store_true", help="Output JSON result instead of human-readable")
    args = parser.parse_args()

    if not args.api_base or not args.api_key:
        env_base, env_key, env_model = load_llm_config()
        api_base = args.api_base or env_base
        api_key = args.api_key or env_key
        model = args.model or env_model
    else:
        api_base, api_key, model = args.api_base, args.api_key, args.model

    if args.session_id == "auto" or args.session_id is None:
        # Process all high-pressure sessions
        conn = get_state_db()
        try:
            cur = conn.execute("""
                SELECT id, api_call_count, message_count, input_tokens
                FROM sessions WHERE archived = 0
            """)
            targets = []
            for sid, api, msgs, in_tok in cur.fetchall():
                p_api = (api or 0) / 200
                p_msgs = (msgs or 0) / 300
                p_tok = ((in_tok or 0) / 200_000) / max(api or 1, 1)
                p = max(p_api, p_msgs, p_tok)
                if p >= COMPRESS_PRESSURE:
                    targets.append((sid, p))
        finally:
            conn.close()

        print(f"🔍 Found {len(targets)} sessions at compress pressure (≥{COMPRESS_PRESSURE:.0%})")
        results = []
        for sid, p in targets:
            r = process_session(sid, api_base, api_key, model, args.force, args.dry_run)
            results.append(r)
        if args.json:
            print(json.dumps(results, indent=2, default=str))
        else:
            # Human-readable summary
            for r in results:
                action = r.get("action", "?")
                icon = {"compress": "✅", "fork": "🚨", "skip": "⏭️", "error": "❌"}.get(action, "?")
                print(f"  {icon} {r.get('sid', '?')[:32]}... → {action}")
                if "deactivated" in r:
                    print(f"      deactivated {r['deactivated']} msgs, summary len={r.get('summary_length', 0)}")
                if "error" in r:
                    print(f"      error: {r['error']}")
    else:
        result = process_session(args.session_id, api_base, api_key, model, args.force, args.dry_run)
        if args.json:
            print(json.dumps(result, indent=2, default=str))
        else:
            print(json.dumps(result, indent=2, default=str))

    return 0


if __name__ == "__main__":
    sys.exit(main())
