#!/bin/bash
# build.sh — Convert project's docs/*.md to standalone HTML previews in docs/_html/
# Usage: build.sh --project <name> [additional-doc-paths...]
#   --project <name>   Project folder name under ~/www/ (e.g. "ai-mailer")
#   [paths]            Optional extra MD files outside docs/ to render
#
# Conventions:
#   - Source MD:                ~/www/<project>/docs/*.md
#   - Engineering HTML output:  ~/www/<project>/docs/_html/<name>.html
#   - Boss-version HTML output: ~/www/<project>/docs/_html/<name>-boss.html
#   - Boss summary JSON input:  ~/www/<project>/docs/_meta/<name>.json
#                               (generated by Hermes agent loop / kanban CEO worker;
#                                .gitignore'd along with _html/)
#   - Gitignore: docs/_html/ AND docs/_meta/ (both are generated artifacts)
#
# Override mechanism: if MD file contains `## 👀 老闆版摘要` section, the
# boss version uses that content instead of the JSON summary.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_PY="$SCRIPT_DIR/build_html.py"

if [[ ! -f "$BUILD_PY" ]]; then
  echo "ERROR: build_html.py not found at $BUILD_PY" >&2
  exit 1
fi

PROJECT=""
EXTRA_DOCS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project) PROJECT="$2"; shift 2 ;;
    --help|-h)
      head -25 "$0" | tail -22
      exit 0
      ;;
    *) EXTRA_DOCS+=("$1"); shift ;;
  esac
done

if [[ -z "$PROJECT" ]]; then
  echo "ERROR: --project <name> required" >&2
  echo "Usage: $0 --project <name> [extra-md-paths...]" >&2
  exit 1
fi

PROJECT_DIR="$HOME/www/$PROJECT"
DOCS_DIR="$PROJECT_DIR/docs"
OUT_DIR="$DOCS_DIR/_html"
META_DIR="$DOCS_DIR/_meta"

if [[ ! -d "$DOCS_DIR" ]]; then
  echo "ERROR: docs dir not found: $DOCS_DIR" >&2
  exit 1
fi

mkdir -p "$OUT_DIR" "$META_DIR"

# Collect source MD files: everything in docs/*.md plus any extras
declare -a SOURCES=()
shopt -s nullglob
for md in "$DOCS_DIR"/*.md; do
  [[ "$md" == "$OUT_DIR"* ]] && continue
  SOURCES+=("$md")
done
shopt -u nullglob
for extra in "${EXTRA_DOCS[@]:-}"; do
  if [[ -f "$extra" ]]; then
    SOURCES+=("$extra")
  fi
done

if [[ ${#SOURCES[@]} -eq 0 ]]; then
  echo "No .md files found in $DOCS_DIR" >&2
  exit 1
fi

BUILT_ENG=0
BUILT_BOSS=0
for src in "${SOURCES[@]}"; do
  fname="$(basename "$src" .md)"
  out_eng="$OUT_DIR/$fname.html"
  out_boss="$OUT_DIR/$fname-boss.html"
  json_path="$META_DIR/$fname.json"
  built_at="$(date '+%Y-%m-%d %H:%M:%S %Z')"

  # 1. Engineering version
  python3 "$BUILD_PY" engineering "$src" "$out_eng" "$fname" "$PROJECT" "$built_at"
  BUILT_ENG=$((BUILT_ENG + 1))

  # 2. Boss version
  python3 "$BUILD_PY" boss "$src" "$out_boss" "$fname" "$PROJECT" "$built_at" "$json_path"
  BUILT_BOSS=$((BUILT_BOSS + 1))

  # Show boss version status (placeholder vs real)
  if [[ -f "$json_path" ]] || grep -q "## 👀 老闆版摘要" "$src" 2>/dev/null; then
    echo "  ✓ $(basename "$src") → docs/_html/$fname.html + docs/_html/$fname-boss.html"
  else
    echo "  ⚠ $(basename "$src") → docs/_html/$fname.html + docs/_html/$fname-boss.html (boss: placeholder — needs JSON or override)"
  fi
done

echo ""
echo "Built $BUILT_ENG engineering + $BUILT_BOSS boss-version HTML preview(s) for project '$PROJECT' at:"
echo "  $OUT_DIR"
echo ""
echo "Open with:"
echo "  open \"$OUT_DIR\""
